services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:jbahmida
    container_name: mariadb
    env_file: .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$(cat /run/secrets/db_root_password) --silent"]
      interval: 3s
      timeout: 3s
      retries: 20
      start_period: 30s
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:jbahmida
    container_name: wordpress
    env_file: .env
    secrets: [db_password, credentials]
    volumes: [wordpress_data:/var/www/html]
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "php-fpm8.2 -t && nc -z localhost 9000"]
      interval: 2s
      timeout: 3s
      retries: 15
      start_period: 5s
    networks: [inception]
    restart: on-failure


  nginx:
    build: ./requirements/nginx
    image: nginx:jbahmida
    container_name: nginx
    env_file: .env
    environment:
      - MY_DOMAIN=${DOMAIN_NAME}
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - inception
    restart: on-failure

  cadvisor:
    build: ./requirements/bonus/cadvisor
    image: cadvisor:jbahmida
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices:
      - /dev/kmsg
    networks:
      - inception

  uptime-kuma:
    build: ./requirements/bonus/uptime_kuma
    image: uptime-kuma:jbahmida
    container_name: uptime-kuma
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=UTC+1
      - UMASK=0022
    networks:
      - inception
    depends_on:
      - nginx
      - wordpress
      - mariadb
    
  redis:
    build: ./requirements/bonus/redis
    image: redis:jbahmida
    container_name: redis
    networks:
      - inception
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 15
      start_period: 5s
    restart: unless-stopped

  ftp:
    build:
      context: ./requirements/bonus/ftp
    image: ftp:jbahmida
    container_name: ftp
    restart: on-failure
    environment:
      FTP_USER: ${FTP_USER}
    secrets:
      - ftp_password
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    networks:
      - inception
    depends_on:
      - wordpress
      
  static-site:
    build: ./requirements/bonus/static-site
    image: static-site:jbahmida
    container_name: static-site
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - inception

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer:jbahmida
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8082:8082"
    networks:
      - inception
    depends_on:
      - mariadb

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/jbahmida/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/jbahmida/data/mariadb
      o: bind
  uptime-kuma_data:
    driver: local
    driver_opts:
      type: none
      device: /home/jbahmida/data/uptime_kuma
      o: bind
networks:
  inception:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt
  ftp_password:
    file: ../secrets/ftp_password.txt